//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GearSimulator.GearManager {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GearSimulator.GearManager.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap AdditionalOptionTooltip_epic {
            get {
                object obj = ResourceManager.GetObject("AdditionalOptionTooltip_epic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap AdditionalOptionTooltip_legendary {
            get {
                object obj = ResourceManager.GetObject("AdditionalOptionTooltip_legendary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap AdditionalOptionTooltip_rare {
            get {
                object obj = ResourceManager.GetObject("AdditionalOptionTooltip_rare", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap AdditionalOptionTooltip_unique {
            get {
                object obj = ResourceManager.GetObject("AdditionalOptionTooltip_unique", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ItemProtector_Icon_0 {
            get {
                object obj = ResourceManager.GetObject("ItemProtector_Icon_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ItemProtector_Icon_1 {
            get {
                object obj = ResourceManager.GetObject("ItemProtector_Icon_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can__ {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can__", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can__1 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can__1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can__2 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can__2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can__3 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can__3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can__4 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can__4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can_0 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can_1 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can_2 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can_3 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can_4 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can_5 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can_6 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can_7 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can_8 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can_9 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can_none {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can_reqDEX {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can_reqDEX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can_reqINT {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can_reqINT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can_reqLEV {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can_reqLEV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can_reqLUK {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can_reqLUK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can_reqPOP {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can_reqPOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Can_reqSTR {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Can_reqSTR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_0 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_1 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_2 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_3 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_4 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_5 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_6 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_7 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_8 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_9 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_minus {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_none {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_percent {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_percent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_plus {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_reqDEX {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_reqDEX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_reqINT {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_reqINT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_reqLEV {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_reqLEV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_reqLUK {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_reqLUK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_reqPOP {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_reqPOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Cannot_reqSTR {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Cannot_reqSTR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_0 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_1 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_2 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_3 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_4 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_5 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_6 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_7 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_8 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_9 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_minus {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_none {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_percent {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_percent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_plus {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_reqDEX {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_reqDEX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_reqINT {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_reqINT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_reqLEV {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_reqLEV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_reqLUK {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_reqLUK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_reqPOP {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_reqPOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Disabled_reqSTR {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Disabled_reqSTR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Job_disable_0 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Job_disable_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Job_disable_1 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Job_disable_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Job_disable_2 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Job_disable_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Job_disable_3 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Job_disable_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Job_disable_4 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Job_disable_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Job_disable_5 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Job_disable_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Job_enable_0 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Job_enable_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Job_enable_1 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Job_enable_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Job_enable_2 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Job_enable_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Job_enable_3 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Job_enable_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Job_enable_4 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Job_enable_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Job_enable_5 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Job_enable_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Job_expand {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Job_expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Job_normal {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Job_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_LookAhead__ {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_LookAhead__", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_LookAhead__1 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_LookAhead__1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_LookAhead__2 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_LookAhead__2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_LookAhead_0 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_LookAhead_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_LookAhead_1 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_LookAhead_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_LookAhead_2 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_LookAhead_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_LookAhead_3 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_LookAhead_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_LookAhead_4 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_LookAhead_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_LookAhead_5 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_LookAhead_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_LookAhead_6 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_LookAhead_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_LookAhead_7 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_LookAhead_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_LookAhead_8 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_LookAhead_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_LookAhead_9 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_LookAhead_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_LookAhead_none {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_LookAhead_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Star_Star {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Star_Star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Star_Star0 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Star_Star0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Star_Star1 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Star_Star1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_decline_0 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_decline_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_decline_1 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_decline_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_decline_2 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_decline_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_decline_3 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_decline_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_decline_4 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_decline_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_decline_5 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_decline_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_decline_6 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_decline_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_decline_7 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_decline_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_decline_8 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_decline_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_decline_9 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_decline_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_decline_minus {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_decline_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_icon_bdr {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_icon_bdr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_icon_igpddr {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_icon_igpddr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_icon_pdd {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_icon_pdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_incline_0 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_incline_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_incline_1 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_incline_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_incline_2 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_incline_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_incline_3 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_incline_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_incline_4 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_incline_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_incline_5 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_incline_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_incline_6 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_incline_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_incline_7 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_incline_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_incline_8 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_incline_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_incline_9 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_incline_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_Summary_incline_plus {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_Summary_incline_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_YellowNumber__ {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_YellowNumber__", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_YellowNumber__1 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_YellowNumber__1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_YellowNumber__2 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_YellowNumber__2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_YellowNumber_0 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_YellowNumber_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_YellowNumber_1 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_YellowNumber_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_YellowNumber_2 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_YellowNumber_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_YellowNumber_3 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_YellowNumber_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_YellowNumber_4 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_YellowNumber_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_YellowNumber_5 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_YellowNumber_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_YellowNumber_6 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_YellowNumber_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_YellowNumber_7 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_YellowNumber_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_YellowNumber_8 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_YellowNumber_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_YellowNumber_9 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_YellowNumber_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Equip_YellowNumber_none {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Equip_YellowNumber_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Frame_bottom {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Frame_bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Frame_cover {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Frame_cover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Frame_dotline {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Frame_dotline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Frame_line {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Frame_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_Frame_top {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_Frame_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_ItemIcon_0 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_ItemIcon_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_ItemIcon_1 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_ItemIcon_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_ItemIcon_2 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_ItemIcon_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_ItemIcon_3 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_ItemIcon_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_ItemIcon_4 {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_ItemIcon_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_ItemIcon_base {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_ItemIcon_base", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_ItemIcon_cover {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_ItemIcon_cover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_ItemIcon_new {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_ItemIcon_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_ItemIcon_old {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_ItemIcon_old", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap UIToolTip_img_Item_ItemIcon_shade {
            get {
                object obj = ResourceManager.GetObject("UIToolTip_img_Item_ItemIcon_shade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
